"""Human- and machine-readable report formatting for diagnoses."""

from __future__ import annotations

import json
from typing import Dict

from .metrics import Diagnosis


def to_dict(d: Diagnosis) -> Dict:
    """Flatten a :class:`Diagnosis` into a JSON-serializable dict."""
    return {
        "loss": d.loss_name,
        "domain": d.domain_name,
        "verdict": d.verdict,
        "flags": d.flags,
        "wrong_region_mean_grad": {f"target={k:g}": v for k, v in d.wrong_region_grad.items()},
        "grad_peak": d.grad_peak,
        "ambiguity_force": d.ambiguity_force,
        "trivial_response": {f"ŷ={k:g}": v for k, v in d.trivial_response.items()},
        "min_loss": d.min_loss,
        "max_curvature": d.max_curvature,
    }


def to_json(d: Diagnosis, indent: int = 2) -> str:
    return json.dumps(to_dict(d), indent=indent, ensure_ascii=False)


def to_markdown(d: Diagnosis) -> str:
    """A compact Markdown row block for one diagnosis."""
    lines = [
        f"### {d.loss_name} — `{d.domain_name}` — **{d.verdict}**",
        "",
    ]
    if d.flags:
        lines.append("**Flags:**")
        for f in d.flags:
            lines.append(f"- ⚠️ {f}")
    else:
        lines.append("**Flags:** none (healthy)")
    lines.append("")
    lines.append("| metric | value |")
    lines.append("|---|---|")
    lines.append(f"| wrong-region mean \\|g\\| | {_fmt_map(d.wrong_region_grad)} |")
    lines.append(f"| gradient peak \\|g\\| | {d.grad_peak:.3g} |")
    lines.append(f"| ambiguity-escape force | {_fmt(d.ambiguity_force)} |")
    lines.append(f"| min loss | {d.min_loss:.3g} |")
    lines.append(f"| max curvature \\|h\\| | {d.max_curvature:.3g} |")
    lines.append("")
    lines.append("**Trivial-solution response:**")
    lines.append("")
    lines.append("| constant output | loss |")
    lines.append("|---|---|")
    for k, v in d.trivial_response.items():
        lines.append(f"| ŷ={k:g} | {v:.3g} |")
    lines.append("")
    return "\n".join(lines)


def format_report(diagnoses) -> str:
    """Format a list of :class:`Diagnosis` as a full Markdown report."""
    if not isinstance(diagnoses, (list, tuple)):
        diagnoses = [diagnoses]
    head = [
        "# Loss-Scout diagnostic report",
        "",
        "Generated by `loss-scout` (model-free output-space scan).",
        "`∂L/∂ŷ` = pull force · `∂²L/∂ŷ²` = curvature.",
        "",
    ]
    body = "\n".join(to_markdown(d) for d in diagnoses)
    return "\n".join(head) + body + "\n"


def _fmt(v) -> str:
    return "—" if v is None else f"{v:.3g}"


def _fmt_map(m: Dict[float, float]) -> str:
    return ", ".join(f"t={k:g}:{v:.3g}" for k, v in m.items())
